name: 'Sharepoint Sync'

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Cloning repo
      uses: actions/checkout@v2

    - name: Copy to SharePoint
      uses: jfabry-noc/SharePointCopy@830ecd32e4048369f7b3d754f21609a60104464d
      with:
       tenant_id: ${{ secrets.TENANT_ID }}
       spo_path: ${{ secrets.SPO_PATH }}
       client_id: ${{ secrets.CLIENT_ID }}
       client_secret: ${{ secrets.CLIENT_SECRET }}
       logging: INFO
