name: 'Sharepoint Sync'

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Cloning repo
      uses: actions/checkout@v2

    - name: Copy to SharePoint
      uses: jfabry-noc/SharePointOnlineCopy@da57060da5e36514c60eae2dc3393ec863c7d9fc
      with:
       spobkp_authority: ${{ secrets.SPOBKP_AUTHORITY }}
       spobkp_endpoint: ${{ secrets.SPOBKP_ENDPOINT }}
       spobkp_clientid: ${{ secrets.SPOBKP_CLIENTID }}
       spobkp_secret: ${{ secrets.SPOBKP_SECRET }}
