name: 'Sharepoint Sync'

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Cloning repo
      uses: actions/checkout@v2

    - name: Copy to SharePoint
      uses: jfabry-noc/SharePointCopy@69628af78e59c4d813591bd3821cfbd987dc64e9
      with:
       tenant_id: ${{ secrets.TENANT_ID }}
       spo_path: ${{ secrets.SPO_PATH }}
       client_id: ${{ secrets.CLIENT_ID }}
       client_secret: ${{ secrets.CLIENT_SECRET }}
       logging: DEBUG
